on:
  workflow_run:
    workflows: ["Python Linting with Flake8"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    needs: PythonLint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish Dockerfile
        run: |
          echo $CR_PAT | docker login ghcr.io -u rodrigoyjcordeiro --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}