on:
  workflow_run:
    workflows: ["Flake8"]
    types:
      - completed

env:
  CR_PAT: ${{ secrets.CR_PAT }}

jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ env.CR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Get Git commit SHA
        id: git_commit
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ steps.git_commit.outputs.sha }} .

      - name: Push Docker image to GitHub Registry
        run: docker push ghcr.io/${{ github.repository }}:${{ steps.git_commit.outputs.sha }}

      - name: Tag image as latest
        run: docker tag ghcr.io/${{ github.repository }}:${{ steps.git_commit.outputs.sha }} ghcr.io/${{ github.repository }}:latest

      - name: Push latest image to GitHub Registry
        run: docker push ghcr.io/${{ github.repository }}:latest
