on:
  workflow_run:
    workflows: ["Flake8"]
    types:
      - completed

env:
  CR_PAT: ${{ secrets.CR_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ env.CR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image to GitHub Registry
        run: docker push ghcr.io/${{ github.repository }}:latest